
{
    var   a= 10
}


try {
 
    console.log(a)
} catch (error) {
 
  console.error("An error to get  avalue of  a", error.message);
}


console.log("Program continues...");
